PROGRAM ARRAYTEST

INTEGER NUMBERS(5)
INTEGER I

NUMBERS(1) = 10
NUMBERS(2) = 20
NUMBERS(3) = 30
NUMBERS(4) = 40
NUMBERS(5) = 50

DO I = 1, 5
    WRITE(*,*) "NUMBER = ", NUMBERS(I)
END DO

END PROGRAM ARRAYTEST