PROGRAM CHECKNUMBER

INTEGER NUMBER

NUMBER = 25

IF (NUMBER .GT. 10) THEN
    WRITE(*,*) "NUMBER IS GREATER THAN 10"
ELSE
    WRITE(*,*) "NUMBER IS 10 OR LESS"
END IF

END PROGRAM CHECKNUMBER